# Generated by Django 3.2.3 on 2021-08-20 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providervalue',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='providervalue',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
