# Generated by Django 3.2.3 on 2022-04-19 23:51

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_merge_0001_initial_0002_create_base_groups'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authapp.customergroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.CharField(default=core.models.get_uuid_token, max_length=36),
        ),
    ]
