version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: ['sh', '/entrypoint.sh']
    volumes:
      - .:/code
    ports:
      - "9000:8000"
    links:
      - "db:postgres_db"
      - "redis:redis_host"
    depends_on:
      - db
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'ascuv_emulator'
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    ports:
      - '8888:5432'
    expose:
      - '5432'
  worker:
    build: .
    command: celery -A ascuv_emulator worker -l info -f celery.logs -B
    links:
      - "redis:redis_host"
      - "db:postgres_db"
    volumes:
      - .:/code
    depends_on:
      - db
      - web
