# Generated by Django 3.2.3 on 2022-04-18 14:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def create_base_group(apps, schema_editor):
    Group = apps.get_model('authapp', 'CustomerGroup')
    Group.objects.create(
        group_name='Standard'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_base_group, reverse_code=migrations.RunPython.noop)
    ]
