# Generated by Django 3.2.3 on 2022-04-19 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('authapp', '0002_create_base_groups'),
    ]

    operations = [
    ]
