# Generated by Django 3.2.6 on 2021-08-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providervalue',
            old_name='received_at',
            new_name='sent_at',
        ),
    ]
